HAI 1.3

HOW IZ I ADAPTEREMIT YR EVENT
  NOT I IZ TRANSPORT'Z IOWRITE YR EVENT MKAY, O RLY?
    YA RLY
      I IZ TRANSPORT'Z ABORT YR "adapter controller write failed" MKAY
  OIC
IF U SAY SO

HOW IZ I ADAPTERERROR YR ID AN YR NAME AN YR MESSAGE AN YR DATA
  I HAS A ERROR ITZ "{}"
  ERROR R I IZ TRANSPORT'Z JSONSET YR ERROR AN YR "name" AN YR I IZ CONVEXJSONSTRING YR NAME MKAY MKAY
  ERROR R I IZ TRANSPORT'Z JSONSET YR ERROR AN YR "message" AN YR I IZ CONVEXJSONSTRING YR MESSAGE MKAY MKAY
  BOTH OF DIFFRINT DATA AN "" AN DIFFRINT DATA AN "null", O RLY?
    YA RLY
      ERROR R I IZ TRANSPORT'Z JSONSET YR ERROR AN YR "data" AN YR DATA MKAY
  OIC
  I HAS A EVENT ITZ "{}"
  EVENT R I IZ TRANSPORT'Z JSONSET YR EVENT AN YR "type" AN YR I IZ CONVEXJSONSTRING YR "error" MKAY MKAY
  DIFFRINT ID AN "", O RLY?
    YA RLY
      EVENT R I IZ TRANSPORT'Z JSONSET YR EVENT AN YR "id" AN YR I IZ CONVEXJSONSTRING YR ID MKAY MKAY
  OIC
  EVENT R I IZ TRANSPORT'Z JSONSET YR EVENT AN YR "error" AN YR ERROR MKAY
  I IZ ADAPTEREMIT YR EVENT MKAY
IF U SAY SO

HOW IZ I ADAPTERSIMPLE YR ID AN YR TYPE
  I HAS A EVENT ITZ "{}"
  EVENT R I IZ TRANSPORT'Z JSONSET YR EVENT AN YR "id" AN YR I IZ CONVEXJSONSTRING YR ID MKAY MKAY
  EVENT R I IZ TRANSPORT'Z JSONSET YR EVENT AN YR "type" AN YR I IZ CONVEXJSONSTRING YR TYPE MKAY MKAY
  I IZ ADAPTEREMIT YR EVENT MKAY
IF U SAY SO

HOW IZ I ADAPTERHTTP YR ID AN YR OP AN YR PATH AN YR ARGS
  I HAS A RESULT ITZ I IZ CONVEXNEWRESULT MKAY
  BOTH SAEM OP AN "query", O RLY?
    YA RLY
      RESULT R I IZ CONVEXQUERY YR PATH AN YR ARGS MKAY
    MEBBE BOTH SAEM OP AN "mutation"
      RESULT R I IZ CONVEXMUTATIONWITHKEY YR PATH AN YR ARGS AN YR ID MKAY
    MEBBE BOTH SAEM OP AN "action"
      RESULT R I IZ CONVEXACTION YR PATH AN YR ARGS MKAY
  OIC
  RESULT'Z OK, O RLY?
    YA RLY
      I HAS A EVENT ITZ "{}"
      EVENT R I IZ TRANSPORT'Z JSONSET YR EVENT AN YR "id" AN YR I IZ CONVEXJSONSTRING YR ID MKAY MKAY
      EVENT R I IZ TRANSPORT'Z JSONSET YR EVENT AN YR "type" AN YR I IZ CONVEXJSONSTRING YR "result" MKAY MKAY
      EVENT R I IZ TRANSPORT'Z JSONSET YR EVENT AN YR "value" AN YR RESULT'Z VALUE MKAY
      EVENT R I IZ TRANSPORT'Z JSONSET YR EVENT AN YR "logs" AN YR RESULT'Z LOGS MKAY
      I IZ ADAPTEREMIT YR EVENT MKAY
    NO WAI
      I HAS A ERROR ITZ "{}"
      ERROR R I IZ TRANSPORT'Z JSONSET YR ERROR AN YR "name" AN YR I IZ CONVEXJSONSTRING YR RESULT'Z ERRORNAME MKAY MKAY
      ERROR R I IZ TRANSPORT'Z JSONSET YR ERROR AN YR "message" AN YR I IZ CONVEXJSONSTRING YR RESULT'Z ERRORMESSAGE MKAY MKAY
      BOTH OF DIFFRINT RESULT'Z ERRORDATA AN "" AN DIFFRINT RESULT'Z ERRORDATA AN "null", O RLY?
        YA RLY
          ERROR R I IZ TRANSPORT'Z JSONSET YR ERROR AN YR "data" AN YR RESULT'Z ERRORDATA MKAY
      OIC
      I HAS A EVENT ITZ "{}"
      EVENT R I IZ TRANSPORT'Z JSONSET YR EVENT AN YR "id" AN YR I IZ CONVEXJSONSTRING YR ID MKAY MKAY
      EVENT R I IZ TRANSPORT'Z JSONSET YR EVENT AN YR "type" AN YR I IZ CONVEXJSONSTRING YR "error" MKAY MKAY
      EVENT R I IZ TRANSPORT'Z JSONSET YR EVENT AN YR "error" AN YR ERROR MKAY
      RESULT'Z HASLOGS, O RLY?
        YA RLY
          EVENT R I IZ TRANSPORT'Z JSONSET YR EVENT AN YR "logs" AN YR RESULT'Z LOGS MKAY
      OIC
      I IZ ADAPTEREMIT YR EVENT MKAY
  OIC
IF U SAY SO

I HAS A CONTROLLEROPEN ITZ TRANSPORT IZ IOOPEN MKAY
NOT CONTROLLEROPEN, O RLY?
  YA RLY
    I IZ TRANSPORT'Z ABORT YR "failed to open adapter controller stream" MKAY
OIC

I HAS A ADAPTERDONE ITZ FAIL
IM IN YR OWNERLOOP
  ADAPTERDONE, O RLY?
    YA RLY
      GTFO
  OIC
  BTW This is the only loop allowed to touch the WebSocket owner.
  I HAS A LIVEEVENT ITZ I IZ CONVEXLIVETICK MKAY
  DIFFRINT LIVEEVENT AN "", O RLY?
    YA RLY
      I IZ ADAPTEREMIT YR LIVEEVENT MKAY
  OIC

  IM IN YR COMMANDONCE
  I HAS A LINE ITZ I IZ TRANSPORT'Z IOREAD YR 20 MKAY
  I HAS A IOSTATUS ITZ TRANSPORT IZ IOSTATUS MKAY
  BOTH SAEM IOSTATUS AN 0, O RLY?
    YA RLY
      GTFO BTW leave this switch, not the owner loop
  OIC
  DIFFRINT IOSTATUS AN 1, O RLY?
    YA RLY
      I IZ CONVEXCLOSELIVE MKAY
      ADAPTERDONE R WIN
      GTFO
  OIC
  NOT I IZ TRANSPORT'Z JSONVALID YR LINE MKAY, O RLY?
    YA RLY
      I IZ ADAPTERERROR YR "" AN YR "ProtocolError" AN YR "invalid adapter JSON" AN YR "null" MKAY
      GTFO
  OIC
  DIFFRINT I IZ TRANSPORT'Z JSONTYPE YR LINE MKAY AN "object", O RLY?
    YA RLY
      I IZ ADAPTERERROR YR "" AN YR "ProtocolError" AN YR "adapter command must be an object" AN YR "null" MKAY
      GTFO
  OIC
  I HAS A ID ITZ I IZ TRANSPORT'Z JSONSTRING YR I IZ TRANSPORT'Z JSONGET YR LINE AN YR "id" MKAY MKAY
  I HAS A OP ITZ I IZ TRANSPORT'Z JSONSTRING YR I IZ TRANSPORT'Z JSONGET YR LINE AN YR "op" MKAY MKAY
  EITHER OF BOTH SAEM ID AN "" AN BOTH SAEM OP AN "", O RLY?
    YA RLY
      I IZ ADAPTERERROR YR "" AN YR "ProtocolError" AN YR "adapter command requires string id and op" AN YR "null" MKAY
      GTFO
  OIC
  OP, WTF?
    OMG "hello"
      I HAS A EVENT ITZ "{}"
      EVENT R I IZ TRANSPORT'Z JSONSET YR EVENT AN YR "protocolVersion" AN YR 1 MKAY
      EVENT R I IZ TRANSPORT'Z JSONSET YR EVENT AN YR "id" AN YR I IZ CONVEXJSONSTRING YR ID MKAY MKAY
      EVENT R I IZ TRANSPORT'Z JSONSET YR EVENT AN YR "type" AN YR I IZ CONVEXJSONSTRING YR "ready" MKAY MKAY
      EVENT R I IZ TRANSPORT'Z JSONSET YR EVENT AN YR "language" AN YR I IZ CONVEXJSONSTRING YR "lolcode" MKAY MKAY
      EVENT R I IZ TRANSPORT'Z JSONSET YR EVENT AN YR "implementation" AN YR I IZ CONVEXJSONSTRING YR "native" MKAY MKAY
      EVENT R I IZ TRANSPORT'Z JSONSET YR EVENT AN YR "runtime" AN YR I IZ CONVEXJSONSTRING YR "lci 0.11.2" MKAY MKAY
      I IZ ADAPTEREMIT YR EVENT MKAY
      GTFO
    OMG "setAuth"
      I HAS A TOKENJSON ITZ I IZ TRANSPORT'Z JSONGET YR LINE AN YR "token" MKAY
      DIFFRINT I IZ TRANSPORT'Z JSONTYPE YR TOKENJSON MKAY AN "string", O RLY?
        YA RLY
          I IZ ADAPTERERROR YR ID AN YR "ProtocolError" AN YR "token must be a string" AN YR "null" MKAY
        NO WAI
          I IZ CONVEXSETAUTH YR I IZ TRANSPORT'Z JSONSTRING YR TOKENJSON MKAY MKAY
          I IZ ADAPTERSIMPLE YR ID AN YR "ack" MKAY
      OIC
      GTFO
    OMG "query"
    OMG "mutation"
    OMG "action"
      I HAS A PATHJSON ITZ I IZ TRANSPORT'Z JSONGET YR LINE AN YR "path" MKAY
      I HAS A ARGS ITZ I IZ TRANSPORT'Z JSONGET YR LINE AN YR "args" MKAY
      BOTH OF BOTH SAEM I IZ TRANSPORT'Z JSONTYPE YR PATHJSON MKAY AN "string" AN BOTH SAEM I IZ TRANSPORT'Z JSONTYPE YR ARGS MKAY AN "object", O RLY?
        YA RLY
          I IZ ADAPTERHTTP YR ID AN YR OP AN YR I IZ TRANSPORT'Z JSONSTRING YR PATHJSON MKAY AN YR ARGS MKAY
        NO WAI
          I IZ ADAPTERERROR YR ID AN YR "ProtocolError" AN YR "path and args are invalid" AN YR "null" MKAY
      OIC
      GTFO
    OMG "subscribe"
      I HAS A SUBJSON ITZ I IZ TRANSPORT'Z JSONGET YR LINE AN YR "subscriptionId" MKAY
      I HAS A PATHJSON ITZ I IZ TRANSPORT'Z JSONGET YR LINE AN YR "path" MKAY
      I HAS A ARGS ITZ I IZ TRANSPORT'Z JSONGET YR LINE AN YR "args" MKAY
      BOTH OF BOTH SAEM I IZ TRANSPORT'Z JSONTYPE YR SUBJSON MKAY AN "string" AN BOTH OF BOTH SAEM I IZ TRANSPORT'Z JSONTYPE YR PATHJSON MKAY AN "string" AN BOTH SAEM I IZ TRANSPORT'Z JSONTYPE YR ARGS MKAY AN "object", O RLY?
        YA RLY
          I IZ CONVEXSUBSCRIBE YR I IZ TRANSPORT'Z JSONSTRING YR SUBJSON MKAY AN YR I IZ TRANSPORT'Z JSONSTRING YR PATHJSON MKAY AN YR ARGS MKAY, O RLY?
            YA RLY
              I IZ ADAPTERSIMPLE YR ID AN YR "ack" MKAY
            NO WAI
              I IZ ADAPTERERROR YR ID AN YR "TransportError" AN YR "Live subscription could not connect" AN YR "null" MKAY
          OIC
        NO WAI
          I IZ ADAPTERERROR YR ID AN YR "ProtocolError" AN YR "subscriptionId, path, and args are invalid" AN YR "null" MKAY
      OIC
      GTFO
    OMG "unsubscribe"
      I HAS A SUBJSON ITZ I IZ TRANSPORT'Z JSONGET YR LINE AN YR "subscriptionId" MKAY
      BOTH SAEM I IZ TRANSPORT'Z JSONTYPE YR SUBJSON MKAY AN "string", O RLY?
        YA RLY
          I IZ CONVEXUNSUBSCRIBE YR I IZ TRANSPORT'Z JSONSTRING YR SUBJSON MKAY MKAY, O RLY?
            YA RLY
              I IZ ADAPTERSIMPLE YR ID AN YR "ack" MKAY
            NO WAI
              I IZ ADAPTERERROR YR ID AN YR "TransportError" AN YR "Live unsubscribe failed" AN YR "null" MKAY
          OIC
        NO WAI
          I IZ ADAPTERERROR YR ID AN YR "ProtocolError" AN YR "subscriptionId must be a string" AN YR "null" MKAY
      OIC
      GTFO
    OMG "debugDisconnect"
      I IZ CONVEXDEBUGDISCONNECT MKAY, O RLY?
        YA RLY
          I IZ ADAPTERSIMPLE YR ID AN YR "ack" MKAY
        NO WAI
          I IZ ADAPTERERROR YR ID AN YR "TransportError" AN YR "Live reconnect failed" AN YR "null" MKAY
      OIC
      GTFO
    OMG "close"
      I IZ CONVEXCLOSELIVE MKAY
      I IZ ADAPTERSIMPLE YR ID AN YR "closed" MKAY
      ADAPTERDONE R WIN
      GTFO
    OMGWTF
      I IZ ADAPTERERROR YR ID AN YR "ProtocolError" AN YR "unsupported adapter operation" AN YR "null" MKAY
  OIC
  GTFO
  IM OUTTA YR COMMANDONCE
IM OUTTA YR OWNERLOOP

KTHXBYE
