(load "/project/client/convex.scm")

(define auth-token #f)

(define (event pairs) (json-write-string pairs))
(define (emit pairs) (display (event pairs)) (newline) (force-output))

(define (error-event id name message)
  `(("id" . ,id) ("type" . "error") ("error" . (("name" . ,name) ("message" . ,message) ("data" . null)))))

(define (run-call command)
  (let* ((op (object-ref command "op"))
         (id (object-ref command "id"))
         (path (object-ref command "path"))
         (args (object-ref command "args"))
         (result ((cond ((string=? op "query") convex-query)
                        ((string=? op "mutation") convex-mutation)
                        ((string=? op "action") convex-action)
                        (else (error "unknown call operation"))) path args auth-token)))
    (if (object-ref result "ok")
        (emit `(("id" . ,id) ("type" . "result") ("value" . ,(object-ref result "value"))
               ("logs" . ,(object-ref result "logs" '()))))
        (emit `(("id" . ,id) ("type" . "error") ("error" . ,(object-ref result "error")))))))

(define (handle command)
  (let ((id (object-ref command "id")) (op (object-ref command "op")))
    (cond
      ((string=? op "hello")
       (if (= (object-ref command "protocolVersion" -1) 1)
           (emit `(("id" . ,id) ("type" . "ready") ("protocolVersion" . 1)
                  ("language" . "scheme") ("implementation" . "native-guile-scheme-http")
                  ("runtime" . "GNU Guile 3.0.8")))
           (emit (error-event id "ProtocolError" "Unsupported adapter protocol version"))))
      ((member op '("query" "mutation" "action"))
       (catch #t (lambda () (run-call command))
         (lambda (_ . args) (emit (error-event id "TransportError" (format #f "~a" args))))))
      ((string=? op "setAuth")
       (set! auth-token (let ((token (object-ref command "token"))) (if (string-null? token) #f token)))
       (emit `(("id" . ,id) ("type" . "ack"))))
      ((member op '("subscribe" "unsubscribe" "debugDisconnect"))
       (emit (error-event id "ProtocolError" "Live WebSocket support is not implemented")))
      ((string=? op "close") (emit `(("id" . ,id) ("type" . "closed"))) 'close)
      (else (emit (error-event id "ProtocolError" "Unknown adapter operation"))))))

(let loop ((line (read-line)))
  (unless (eof-object? line)
    (let ((result (catch #t (lambda () (handle (json-read-string line)))
                    (lambda (_ . args) (emit (error-event "invalid" "ProtocolError" (format #f "~a" args)))))))
      (unless (eq? result 'close) (loop (read-line))))))
