HAI 1.3

CAN HAS TRANSPORT?

HOW IZ I CONVEXCLIENTVERSION
  FOUND YR "lolcode-0.1.0"
IF U SAY SO

HOW IZ I CONVEXJSONSTRING YR TEXT
  FOUND YR I IZ TRANSPORT'Z JSONESCAPE YR TEXT MKAY
IF U SAY SO

KTHXBYE
