HAI 1.3

CAN HAS TRANSPORT?
CAN HAS STRING?

I HAS A CONVEXAUTHTOKEN ITZ ""

HOW IZ I CONVEXCLIENTVERSION
  FOUND YR "lolcode-0.1.0"
IF U SAY SO

HOW IZ I CONVEXJSONSTRING YR TEXT
  FOUND YR I IZ TRANSPORT'Z JSONESCAPE YR TEXT MKAY
IF U SAY SO

HOW IZ I CONVEXSETAUTH YR TOKEN
  CONVEXAUTHTOKEN R TOKEN
IF U SAY SO

BTW A result is a BUKKIT so callers can preserve structured Convex failures
BTW without turning an error response into a successful JSON value.
HOW IZ I CONVEXNEWRESULT
  I HAS A RESULT ITZ A BUKKIT
  RESULT HAS A OK ITZ FAIL
  RESULT HAS A VALUE ITZ ""
  RESULT HAS A LOGS ITZ "[]"
  RESULT HAS A HASLOGS ITZ FAIL
  RESULT HAS A ERRORNAME ITZ ""
  RESULT HAS A ERRORMESSAGE ITZ ""
  RESULT HAS A ERRORDATA ITZ "null"
  FOUND YR RESULT
IF U SAY SO

HOW IZ I CONVEXFAIL YR NAME AN YR MESSAGE
  I HAS A RESULT ITZ I IZ CONVEXNEWRESULT MKAY
  RESULT'Z ERRORNAME R NAME
  RESULT'Z ERRORMESSAGE R MESSAGE
  FOUND YR RESULT
IF U SAY SO

HOW IZ I CONVEXSTARTSWITH YR TEXT AN YR PREFIX
  I HAS A TEXTLEN ITZ I IZ STRING'Z LEN YR TEXT MKAY
  I HAS A PREFIXLEN ITZ I IZ STRING'Z LEN YR PREFIX MKAY
  DIFFRINT BIGGR OF TEXTLEN AN PREFIXLEN AN TEXTLEN, O RLY?
    YA RLY
      FOUND YR FAIL
  OIC
  I HAS A MATCH ITZ WIN
  IM IN YR CHECK UPPIN YR INDEX TIL BOTH SAEM INDEX AN PREFIXLEN
    DIFFRINT I IZ STRING'Z AT YR TEXT AN YR INDEX MKAY AN I IZ STRING'Z AT YR PREFIX AN YR INDEX MKAY, O RLY?
      YA RLY
        MATCH R FAIL
        GTFO
    OIC
  IM OUTTA YR CHECK
  FOUND YR MATCH
IF U SAY SO

BTW All Convex-specific envelope fields and response classification are here.
BTW TRANSPORT only performs an ordinary verified HTTP request.
HOW IZ I CONVEXCALL YR OPERATION AN YR PATH AN YR ARGS AN YR IDEMPOTENCYKEY
  I HAS A URL ITZ I IZ TRANSPORT'Z ENV YR "CONVEX_URL" MKAY
  I HAS A HTTPURL ITZ I IZ CONVEXSTARTSWITH YR URL AN YR "http://" MKAY
  I HAS A HTTPSURL ITZ I IZ CONVEXSTARTSWITH YR URL AN YR "https://" MKAY
  NOT EITHER OF HTTPURL AN HTTPSURL, O RLY?
    YA RLY
      FOUND YR I IZ CONVEXFAIL YR "ProtocolError" AN YR "CONVEX_URL must be http(s)" MKAY
  OIC
  NOT I IZ TRANSPORT'Z JSONVALID YR ARGS MKAY, O RLY?
    YA RLY
      FOUND YR I IZ CONVEXFAIL YR "ProtocolError" AN YR "Convex args must be valid JSON" MKAY
  OIC
  DIFFRINT I IZ TRANSPORT'Z JSONTYPE YR ARGS MKAY AN "object", O RLY?
    YA RLY
      FOUND YR I IZ CONVEXFAIL YR "ProtocolError" AN YR "Convex args must be a named JSON object" MKAY
  OIC

  I HAS A BODY ITZ "{}"
  BODY R I IZ TRANSPORT'Z JSONSET YR BODY AN YR "path" AN YR I IZ CONVEXJSONSTRING YR PATH MKAY MKAY
  BODY R I IZ TRANSPORT'Z JSONSET YR BODY AN YR "args" AN YR ARGS MKAY
  BODY R I IZ TRANSPORT'Z JSONSET YR BODY AN YR "format" AN YR I IZ CONVEXJSONSTRING YR "json" MKAY MKAY
  DIFFRINT IDEMPOTENCYKEY AN "", O RLY?
    YA RLY
      BODY R I IZ TRANSPORT'Z JSONSET YR BODY AN YR "idempotencyKey" AN YR I IZ CONVEXJSONSTRING YR IDEMPOTENCYKEY MKAY MKAY
  OIC

  I HAS A HEADERS ITZ "{}"
  HEADERS R I IZ TRANSPORT'Z JSONSET YR HEADERS AN YR "Content-Type" AN YR I IZ CONVEXJSONSTRING YR "application/json" MKAY MKAY
  HEADERS R I IZ TRANSPORT'Z JSONSET YR HEADERS AN YR "Convex-Client" AN YR I IZ CONVEXJSONSTRING YR I IZ CONVEXCLIENTVERSION MKAY MKAY MKAY
  DIFFRINT CONVEXAUTHTOKEN AN "", O RLY?
    YA RLY
      HEADERS R I IZ TRANSPORT'Z JSONSET YR HEADERS AN YR "Authorization" AN YR I IZ CONVEXJSONSTRING YR SMOOSH "Bearer " AN CONVEXAUTHTOKEN MKAY MKAY MKAY
  OIC

  I HAS A ENDPOINT ITZ SMOOSH URL AN "/api/" AN OPERATION MKAY
  I HAS A RESPONSE ITZ I IZ TRANSPORT'Z HTTP YR "POST" AN YR ENDPOINT AN YR HEADERS AN YR BODY AN YR 15000 MKAY
  I HAS A TRANSPORTERROR ITZ I IZ TRANSPORT'Z HTTPERROR YR RESPONSE MKAY
  I HAS A STATUSCODE ITZ I IZ TRANSPORT'Z HTTPSTATUS YR RESPONSE MKAY
  I HAS A RESPONSEBODY ITZ I IZ TRANSPORT'Z HTTPBODY YR RESPONSE MKAY
  I IZ TRANSPORT'Z HTTPFREE YR RESPONSE MKAY

  DIFFRINT TRANSPORTERROR AN "", O RLY?
    YA RLY
      FOUND YR I IZ CONVEXFAIL YR "TransportError" AN YR TRANSPORTERROR MKAY
  OIC
  DIFFRINT STATUSCODE AN 200, O RLY?
    YA RLY
      FOUND YR I IZ CONVEXFAIL YR "TransportError" AN YR SMOOSH "HTTP status " AN STATUSCODE MKAY MKAY
  OIC
  NOT I IZ TRANSPORT'Z JSONVALID YR RESPONSEBODY MKAY, O RLY?
    YA RLY
      FOUND YR I IZ CONVEXFAIL YR "ProtocolError" AN YR "Convex returned malformed JSON" MKAY
  OIC

  I HAS A STATUSJSON ITZ I IZ TRANSPORT'Z JSONGET YR RESPONSEBODY AN YR "status" MKAY
  I HAS A STATUS ITZ I IZ TRANSPORT'Z JSONSTRING YR STATUSJSON MKAY
  BOTH SAEM STATUS AN "success", O RLY?
    YA RLY
      NOT I IZ TRANSPORT'Z JSONHAS YR RESPONSEBODY AN YR "value" MKAY, O RLY?
        YA RLY
          FOUND YR I IZ CONVEXFAIL YR "ProtocolError" AN YR "Convex success omitted value" MKAY
      OIC
      I HAS A RESULT ITZ I IZ CONVEXNEWRESULT MKAY
      RESULT'Z OK R WIN
      RESULT'Z VALUE R I IZ TRANSPORT'Z JSONGET YR RESPONSEBODY AN YR "value" MKAY
      I IZ TRANSPORT'Z JSONHAS YR RESPONSEBODY AN YR "logLines" MKAY, O RLY?
        YA RLY
          RESULT'Z LOGS R I IZ TRANSPORT'Z JSONGET YR RESPONSEBODY AN YR "logLines" MKAY
          RESULT'Z HASLOGS R WIN
      OIC
      FOUND YR RESULT
  OIC
  BOTH SAEM STATUS AN "error", O RLY?
    YA RLY
      I HAS A RESULT ITZ I IZ CONVEXNEWRESULT MKAY
      RESULT'Z ERRORNAME R "FunctionError"
      RESULT'Z ERRORMESSAGE R "Convex function failed"
      I IZ TRANSPORT'Z JSONHAS YR RESPONSEBODY AN YR "errorMessage" MKAY, O RLY?
        YA RLY
          RESULT'Z ERRORMESSAGE R I IZ TRANSPORT'Z JSONSTRING YR I IZ TRANSPORT'Z JSONGET YR RESPONSEBODY AN YR "errorMessage" MKAY MKAY
      OIC
      I IZ TRANSPORT'Z JSONHAS YR RESPONSEBODY AN YR "errorData" MKAY, O RLY?
        YA RLY
          RESULT'Z ERRORDATA R I IZ TRANSPORT'Z JSONGET YR RESPONSEBODY AN YR "errorData" MKAY
      OIC
      I IZ TRANSPORT'Z JSONHAS YR RESPONSEBODY AN YR "logLines" MKAY, O RLY?
        YA RLY
          RESULT'Z LOGS R I IZ TRANSPORT'Z JSONGET YR RESPONSEBODY AN YR "logLines" MKAY
          RESULT'Z HASLOGS R WIN
      OIC
      FOUND YR RESULT
  OIC
  FOUND YR I IZ CONVEXFAIL YR "ProtocolError" AN YR "Convex returned an unknown JSON response" MKAY
IF U SAY SO

HOW IZ I CONVEXQUERY YR PATH AN YR ARGS
  FOUND YR I IZ CONVEXCALL YR "query" AN YR PATH AN YR ARGS AN YR "" MKAY
IF U SAY SO

HOW IZ I CONVEXMUTATION YR PATH AN YR ARGS
  FOUND YR I IZ CONVEXCALL YR "mutation" AN YR PATH AN YR ARGS AN YR I IZ TRANSPORT'Z RANDOMHEX YR 16 MKAY MKAY
IF U SAY SO

HOW IZ I CONVEXMUTATIONWITHKEY YR PATH AN YR ARGS AN YR IDEMPOTENCYKEY
  FOUND YR I IZ CONVEXCALL YR "mutation" AN YR PATH AN YR ARGS AN YR IDEMPOTENCYKEY MKAY
IF U SAY SO

HOW IZ I CONVEXACTION YR PATH AN YR ARGS
  FOUND YR I IZ CONVEXCALL YR "action" AN YR PATH AN YR ARGS AN YR "" MKAY
IF U SAY SO

KTHXBYE
