HAI 1.3

BTW This file is the single owner of every Convex Live state transition.
BTW TRANSPORT only exchanges verified RFC6455 text frames.

I HAS A CONVEXSUBS ITZ A BUKKIT
I HAS A CONVEXEVENTS ITZ A BUKKIT
I HAS A CONVEXNEXTQUERY ITZ 0
I HAS A CONVEXQUERYSET ITZ 0
I HAS A CONVEXREMOTEQUERYSET ITZ 0
I HAS A CONVEXREMOTEIDENTITY ITZ 0
I HAS A CONVEXREMOTETS ITZ "AAAAAAAAAAA="
I HAS A CONVEXMAXTS ITZ ""
I HAS A CONVEXCONNECTED ITZ FAIL
I HAS A CONVEXSOCKET
I HAS A CONVEXCONNECTIONCOUNT ITZ 0
I HAS A CONVEXLASTCLOSE ITZ "InitialConnect"
I HAS A CONVEXBACKOFF ITZ 100
I HAS A CONVEXRECONNECTAT ITZ 0
I HAS A CONVEXEVENTHEAD ITZ 0
I HAS A CONVEXEVENTCOUNT ITZ 0
I HAS A CONVEXEVENTBYTES ITZ 0
I HAS A CONVEXEVENTBYTECAP ITZ 4194304

IM IN YR MAKESLOTS UPPIN YR SLOT TIL BOTH SAEM SLOT AN 16
  I HAS A KEY ITZ SMOOSH "S" AN SLOT MKAY
  CONVEXSUBS HAS A SRS KEY ITZ A BUKKIT
  I HAS A SUB ITZ CONVEXSUBS'Z SRS KEY
  SUB HAS A ACTIVE ITZ FAIL
  SUB HAS A ID ITZ ""
  SUB HAS A PATH ITZ ""
  SUB HAS A ARGS ITZ "{}"
  SUB HAS A QUERYID ITZ 0
  SUB HAS A GENERATION ITZ 0
  SUB HAS A REHYDRATING ITZ FAIL
  SUB HAS A HASLAST ITZ FAIL
  SUB HAS A LASTVALUE ITZ ""
  CONVEXEVENTS HAS A SRS KEY ITZ A BUKKIT
  I HAS A EVENT ITZ CONVEXEVENTS'Z SRS KEY
  EVENT HAS A USED ITZ FAIL
  EVENT HAS A PAYLOAD ITZ ""
  EVENT HAS A BYTES ITZ 0
  EVENT HAS A SUBKEY ITZ ""
  EVENT HAS A GENERATION ITZ 0
IM OUTTA YR MAKESLOTS

HOW IZ I CONVEXSLOTKEY YR INDEX
  FOUND YR SMOOSH "S" AN INDEX MKAY
IF U SAY SO

HOW IZ I CONVEXFINDSUB YR SUBSCRIPTIONID
  IM IN YR FINDLOOP UPPIN YR INDEX TIL BOTH SAEM INDEX AN 16
    I HAS A KEY ITZ I IZ CONVEXSLOTKEY YR INDEX MKAY
    I HAS A SUB ITZ CONVEXSUBS'Z SRS KEY
    BOTH OF SUB'Z ACTIVE AN BOTH SAEM SUB'Z ID AN SUBSCRIPTIONID, O RLY?
      YA RLY
        FOUND YR KEY
    OIC
  IM OUTTA YR FINDLOOP
  FOUND YR ""
IF U SAY SO

HOW IZ I CONVEXFREESUB
  IM IN YR FREELOOP UPPIN YR INDEX TIL BOTH SAEM INDEX AN 16
    I HAS A KEY ITZ I IZ CONVEXSLOTKEY YR INDEX MKAY
    I HAS A SUB ITZ CONVEXSUBS'Z SRS KEY
    NOT SUB'Z ACTIVE, O RLY?
      YA RLY
        FOUND YR KEY
    OIC
  IM OUTTA YR FREELOOP
  FOUND YR ""
IF U SAY SO

HOW IZ I CONVEXFINDQUERY YR QUERYID
  IM IN YR QUERYLOOP UPPIN YR INDEX TIL BOTH SAEM INDEX AN 16
    I HAS A KEY ITZ I IZ CONVEXSLOTKEY YR INDEX MKAY
    I HAS A SUB ITZ CONVEXSUBS'Z SRS KEY
    BOTH OF SUB'Z ACTIVE AN BOTH SAEM SUB'Z QUERYID AN MAEK QUERYID A NUMBR, O RLY?
      YA RLY
        FOUND YR KEY
    OIC
  IM OUTTA YR QUERYLOOP
  FOUND YR ""
IF U SAY SO

HOW IZ I CONVEXHASACTIVESUB
  IM IN YR ACTIVELOOP UPPIN YR INDEX TIL BOTH SAEM INDEX AN 16
    I HAS A KEY ITZ I IZ CONVEXSLOTKEY YR INDEX MKAY
    I HAS A SUB ITZ CONVEXSUBS'Z SRS KEY
    SUB'Z ACTIVE, O RLY?
      YA RLY
        FOUND YR WIN
    OIC
  IM OUTTA YR ACTIVELOOP
  FOUND YR FAIL
IF U SAY SO

BTW Queue memory is bounded by both count and encoded byte size. Oldest events
BTW are discarded under pressure, and generation checks suppress stale relays.
HOW IZ I CONVEXDROPEVENT
  BOTH SAEM CONVEXEVENTCOUNT AN 0, O RLY?
    YA RLY
      FOUND YR FAIL
  OIC
  I HAS A KEY ITZ I IZ CONVEXSLOTKEY YR CONVEXEVENTHEAD MKAY
  I HAS A EVENT ITZ CONVEXEVENTS'Z SRS KEY
  CONVEXEVENTBYTES R DIFF OF CONVEXEVENTBYTES AN EVENT'Z BYTES
  EVENT'Z USED R FAIL
  EVENT'Z PAYLOAD R ""
  EVENT'Z BYTES R 0
  CONVEXEVENTHEAD R MOD OF SUM OF CONVEXEVENTHEAD AN 1 AN 16
  CONVEXEVENTCOUNT R DIFF OF CONVEXEVENTCOUNT AN 1
  FOUND YR WIN
IF U SAY SO

HOW IZ I CONVEXENQUEUE YR PAYLOAD AN YR SUBKEY AN YR GENERATION
  I HAS A BYTES ITZ I IZ STRING'Z LEN YR PAYLOAD MKAY
  DIFFRINT BIGGR OF BYTES AN CONVEXEVENTBYTECAP AN CONVEXEVENTBYTECAP, O RLY?
    YA RLY
      FOUND YR FAIL
  OIC
  IM IN YR MAKEROOM
    I HAS A REQUIRED ITZ SUM OF CONVEXEVENTBYTES AN BYTES
    I HAS A COUNTISFULL ITZ BOTH SAEM CONVEXEVENTCOUNT AN 16
    I HAS A BYTESAREFULL ITZ DIFFRINT SMALLR OF REQUIRED AN CONVEXEVENTBYTECAP AN REQUIRED
    NOT EITHER OF COUNTISFULL AN BYTESAREFULL, O RLY?
      YA RLY
        GTFO
    OIC
    I IZ CONVEXDROPEVENT MKAY
  IM OUTTA YR MAKEROOM
  I HAS A INDEX ITZ MOD OF SUM OF CONVEXEVENTHEAD AN CONVEXEVENTCOUNT AN 16
  I HAS A KEY ITZ I IZ CONVEXSLOTKEY YR INDEX MKAY
  I HAS A EVENT ITZ CONVEXEVENTS'Z SRS KEY
  EVENT'Z USED R WIN
  EVENT'Z PAYLOAD R PAYLOAD
  EVENT'Z BYTES R BYTES
  EVENT'Z SUBKEY R SUBKEY
  EVENT'Z GENERATION R GENERATION
  CONVEXEVENTCOUNT R SUM OF CONVEXEVENTCOUNT AN 1
  CONVEXEVENTBYTES R SUM OF CONVEXEVENTBYTES AN BYTES
  FOUND YR WIN
IF U SAY SO

HOW IZ I CONVEXTAKEEVENT
  IM IN YR TAKELOOP
    BOTH SAEM CONVEXEVENTCOUNT AN 0, O RLY?
      YA RLY
        GTFO
    OIC
    I HAS A KEY ITZ I IZ CONVEXSLOTKEY YR CONVEXEVENTHEAD MKAY
    I HAS A EVENT ITZ CONVEXEVENTS'Z SRS KEY
    I HAS A PAYLOAD ITZ EVENT'Z PAYLOAD
    I HAS A SUBKEY ITZ EVENT'Z SUBKEY
    I HAS A GENERATION ITZ EVENT'Z GENERATION
    I IZ CONVEXDROPEVENT MKAY
    BOTH SAEM SUBKEY AN "", O RLY?
      YA RLY
        FOUND YR PAYLOAD
    OIC
    I HAS A SUB ITZ CONVEXSUBS'Z SRS SUBKEY
    BOTH OF SUB'Z ACTIVE AN BOTH SAEM SUB'Z GENERATION AN GENERATION, O RLY?
      YA RLY
        FOUND YR PAYLOAD
    OIC
  IM OUTTA YR TAKELOOP
  FOUND YR ""
IF U SAY SO

HOW IZ I CONVEXSUBERROR YR SUBKEY AN YR NAME AN YR MESSAGE AN YR DATA
  I HAS A SUB ITZ CONVEXSUBS'Z SRS SUBKEY
  I HAS A EVENT ITZ "{}"
  EVENT R I IZ TRANSPORT'Z JSONSET YR EVENT AN YR "type" AN YR I IZ CONVEXJSONSTRING YR "subscription" MKAY MKAY
  EVENT R I IZ TRANSPORT'Z JSONSET YR EVENT AN YR "subscriptionId" AN YR I IZ CONVEXJSONSTRING YR SUB'Z ID MKAY MKAY
  I HAS A ERROR ITZ "{}"
  ERROR R I IZ TRANSPORT'Z JSONSET YR ERROR AN YR "name" AN YR I IZ CONVEXJSONSTRING YR NAME MKAY MKAY
  ERROR R I IZ TRANSPORT'Z JSONSET YR ERROR AN YR "message" AN YR I IZ CONVEXJSONSTRING YR MESSAGE MKAY MKAY
  BOTH OF DIFFRINT DATA AN "" AN DIFFRINT DATA AN "null", O RLY?
    YA RLY
      ERROR R I IZ TRANSPORT'Z JSONSET YR ERROR AN YR "data" AN YR DATA MKAY
  OIC
  EVENT R I IZ TRANSPORT'Z JSONSET YR EVENT AN YR "error" AN YR ERROR MKAY
  FOUND YR I IZ CONVEXENQUEUE YR EVENT AN YR SUBKEY AN YR SUB'Z GENERATION MKAY
IF U SAY SO

HOW IZ I CONVEXPUBLISHERROR YR NAME AN YR MESSAGE
  IM IN YR ERRORLOOP UPPIN YR INDEX TIL BOTH SAEM INDEX AN 16
    I HAS A KEY ITZ I IZ CONVEXSLOTKEY YR INDEX MKAY
    I HAS A SUB ITZ CONVEXSUBS'Z SRS KEY
    SUB'Z ACTIVE, O RLY?
      YA RLY
        I IZ CONVEXSUBERROR YR KEY AN YR NAME AN YR MESSAGE AN YR "null" MKAY
    OIC
  IM OUTTA YR ERRORLOOP
IF U SAY SO

HOW IZ I CONVEXWSURL
  I HAS A URL ITZ I IZ TRANSPORT'Z ENV YR "CONVEX_URL" MKAY
  I HAS A OUTPUT ITZ ""
  I HAS A START ITZ 0
  I IZ CONVEXSTARTSWITH YR URL AN YR "https://" MKAY, O RLY?
    YA RLY
      OUTPUT R "wss://"
      START R 8
    NO WAI
      I IZ CONVEXSTARTSWITH YR URL AN YR "http://" MKAY, O RLY?
        YA RLY
          OUTPUT R "ws://"
          START R 7
        NO WAI
          FOUND YR ""
      OIC
  OIC
  I HAS A LENGTH ITZ I IZ STRING'Z LEN YR URL MKAY
  IM IN YR COPYURL UPPIN YR INDEX TIL BOTH SAEM INDEX AN LENGTH
    BOTH SAEM BIGGR OF INDEX AN START AN INDEX, O RLY?
      YA RLY
        OUTPUT R SMOOSH OUTPUT AN I IZ STRING'Z AT YR URL AN YR INDEX MKAY MKAY
    OIC
  IM OUTTA YR COPYURL
  FOUND YR SMOOSH OUTPUT AN "/api/sync" MKAY
IF U SAY SO

HOW IZ I CONVEXADDMESSAGE YR SUBKEY
  I HAS A SUB ITZ CONVEXSUBS'Z SRS SUBKEY
  I HAS A MODIFICATION ITZ "{}"
  MODIFICATION R I IZ TRANSPORT'Z JSONSET YR MODIFICATION AN YR "type" AN YR I IZ CONVEXJSONSTRING YR "Add" MKAY MKAY
  MODIFICATION R I IZ TRANSPORT'Z JSONSET YR MODIFICATION AN YR "queryId" AN YR SUB'Z QUERYID MKAY
  MODIFICATION R I IZ TRANSPORT'Z JSONSET YR MODIFICATION AN YR "udfPath" AN YR I IZ CONVEXJSONSTRING YR SUB'Z PATH MKAY MKAY
  I HAS A ARGSARRAY ITZ I IZ TRANSPORT'Z JSONAPPEND YR "[]" AN YR SUB'Z ARGS MKAY
  MODIFICATION R I IZ TRANSPORT'Z JSONSET YR MODIFICATION AN YR "args" AN YR ARGSARRAY MKAY
  I HAS A MODIFICATIONS ITZ I IZ TRANSPORT'Z JSONAPPEND YR "[]" AN YR MODIFICATION MKAY
  I HAS A MESSAGE ITZ "{}"
  MESSAGE R I IZ TRANSPORT'Z JSONSET YR MESSAGE AN YR "type" AN YR I IZ CONVEXJSONSTRING YR "ModifyQuerySet" MKAY MKAY
  MESSAGE R I IZ TRANSPORT'Z JSONSET YR MESSAGE AN YR "baseVersion" AN YR CONVEXQUERYSET MKAY
  MESSAGE R I IZ TRANSPORT'Z JSONSET YR MESSAGE AN YR "newVersion" AN YR SUM OF CONVEXQUERYSET AN 1 MKAY
  MESSAGE R I IZ TRANSPORT'Z JSONSET YR MESSAGE AN YR "modifications" AN YR MODIFICATIONS MKAY
  FOUND YR MESSAGE
IF U SAY SO

HOW IZ I CONVEXREMOVEMESSAGE YR QUERYID
  I HAS A MODIFICATION ITZ "{}"
  MODIFICATION R I IZ TRANSPORT'Z JSONSET YR MODIFICATION AN YR "type" AN YR I IZ CONVEXJSONSTRING YR "Remove" MKAY MKAY
  MODIFICATION R I IZ TRANSPORT'Z JSONSET YR MODIFICATION AN YR "queryId" AN YR QUERYID MKAY
  I HAS A MODIFICATIONS ITZ I IZ TRANSPORT'Z JSONAPPEND YR "[]" AN YR MODIFICATION MKAY
  I HAS A MESSAGE ITZ "{}"
  MESSAGE R I IZ TRANSPORT'Z JSONSET YR MESSAGE AN YR "type" AN YR I IZ CONVEXJSONSTRING YR "ModifyQuerySet" MKAY MKAY
  MESSAGE R I IZ TRANSPORT'Z JSONSET YR MESSAGE AN YR "baseVersion" AN YR CONVEXQUERYSET MKAY
  MESSAGE R I IZ TRANSPORT'Z JSONSET YR MESSAGE AN YR "newVersion" AN YR SUM OF CONVEXQUERYSET AN 1 MKAY
  MESSAGE R I IZ TRANSPORT'Z JSONSET YR MESSAGE AN YR "modifications" AN YR MODIFICATIONS MKAY
  FOUND YR MESSAGE
IF U SAY SO

HOW IZ I CONVEXRETIRE YR REASON AN YR REPORT
  CONVEXCONNECTED, O RLY?
    YA RLY
      I IZ TRANSPORT'Z WSCLOSE YR CONVEXSOCKET AN YR 250 MKAY
      I IZ TRANSPORT'Z WSFREE YR CONVEXSOCKET MKAY
  OIC
  CONVEXCONNECTED R FAIL
  CONVEXCONNECTIONCOUNT R SUM OF CONVEXCONNECTIONCOUNT AN 1
  CONVEXQUERYSET R 0
  CONVEXREMOTEQUERYSET R 0
  CONVEXREMOTEIDENTITY R 0
  CONVEXREMOTETS R "AAAAAAAAAAA="
  CONVEXLASTCLOSE R REASON
  IM IN YR REHYDRATELOOP UPPIN YR INDEX TIL BOTH SAEM INDEX AN 16
    I HAS A KEY ITZ I IZ CONVEXSLOTKEY YR INDEX MKAY
    I HAS A SUB ITZ CONVEXSUBS'Z SRS KEY
    SUB'Z ACTIVE, O RLY?
      YA RLY
        SUB'Z REHYDRATING R WIN
    OIC
  IM OUTTA YR REHYDRATELOOP
  REPORT, O RLY?
    YA RLY
      I IZ CONVEXPUBLISHERROR YR "TransportError" AN YR REASON MKAY
  OIC
IF U SAY SO

HOW IZ I CONVEXCONNECTLIVE
  I HAS A URL ITZ I IZ CONVEXWSURL MKAY
  BOTH SAEM URL AN "", O RLY?
    YA RLY
      FOUND YR FAIL
  OIC
  CONVEXSOCKET R I IZ TRANSPORT'Z WSCONNECT YR URL AN YR 10000 MKAY
  NOT I IZ TRANSPORT'Z WSACTIVE YR CONVEXSOCKET MKAY, O RLY?
    YA RLY
      I IZ TRANSPORT'Z WSFREE YR CONVEXSOCKET MKAY
      FOUND YR FAIL
  OIC
  I HAS A SESSION ITZ SMOOSH I IZ TRANSPORT'Z RANDOMHEX YR 4 MKAY AN "-" AN I IZ TRANSPORT'Z RANDOMHEX YR 2 MKAY AN "-4" AN I IZ TRANSPORT'Z RANDOMHEX YR 2 MKAY AN "-a" AN I IZ TRANSPORT'Z RANDOMHEX YR 2 MKAY AN "-" AN I IZ TRANSPORT'Z RANDOMHEX YR 6 MKAY MKAY
  I HAS A CONNECT ITZ "{}"
  CONNECT R I IZ TRANSPORT'Z JSONSET YR CONNECT AN YR "type" AN YR I IZ CONVEXJSONSTRING YR "Connect" MKAY MKAY
  CONNECT R I IZ TRANSPORT'Z JSONSET YR CONNECT AN YR "sessionId" AN YR I IZ CONVEXJSONSTRING YR SESSION MKAY MKAY
  CONNECT R I IZ TRANSPORT'Z JSONSET YR CONNECT AN YR "connectionCount" AN YR CONVEXCONNECTIONCOUNT MKAY
  CONNECT R I IZ TRANSPORT'Z JSONSET YR CONNECT AN YR "lastCloseReason" AN YR I IZ CONVEXJSONSTRING YR CONVEXLASTCLOSE MKAY MKAY
  CONNECT R I IZ TRANSPORT'Z JSONSET YR CONNECT AN YR "clientTs" AN YR 0 MKAY
  DIFFRINT CONVEXMAXTS AN "", O RLY?
    YA RLY
      CONNECT R I IZ TRANSPORT'Z JSONSET YR CONNECT AN YR "maxObservedTimestamp" AN YR I IZ CONVEXJSONSTRING YR CONVEXMAXTS MKAY MKAY
  OIC
  NOT I IZ TRANSPORT'Z WSSEND YR CONVEXSOCKET AN YR CONNECT AN YR 250 MKAY, O RLY?
    YA RLY
      I IZ TRANSPORT'Z WSFREE YR CONVEXSOCKET MKAY
      FOUND YR FAIL
  OIC
  CONVEXQUERYSET R 0
  IM IN YR REPLAYLOOP UPPIN YR INDEX TIL BOTH SAEM INDEX AN 16
    I HAS A KEY ITZ I IZ CONVEXSLOTKEY YR INDEX MKAY
    I HAS A SUB ITZ CONVEXSUBS'Z SRS KEY
    SUB'Z ACTIVE, O RLY?
      YA RLY
        NOT I IZ TRANSPORT'Z WSSEND YR CONVEXSOCKET AN YR I IZ CONVEXADDMESSAGE YR KEY MKAY AN YR 250 MKAY, O RLY?
          YA RLY
            I IZ TRANSPORT'Z WSFREE YR CONVEXSOCKET MKAY
            FOUND YR FAIL
        OIC
        CONVEXQUERYSET R SUM OF CONVEXQUERYSET AN 1
    OIC
  IM OUTTA YR REPLAYLOOP
  CONVEXCONNECTED R WIN
  CONVEXBACKOFF R 100
  CONVEXRECONNECTAT R 0
  FOUND YR WIN
IF U SAY SO

HOW IZ I CONVEXSCHEDULERECONNECT YR REASON AN YR ERRORNAME
  I IZ CONVEXRETIRE YR REASON AN YR FAIL MKAY
  I IZ CONVEXPUBLISHERROR YR ERRORNAME AN YR REASON MKAY
  CONVEXRECONNECTAT R SUM OF TRANSPORT IZ NOW MKAY AN CONVEXBACKOFF
  CONVEXBACKOFF R SMALLR OF PRODUKT OF CONVEXBACKOFF AN 2 AN 15000
IF U SAY SO

HOW IZ I CONVEXINVALIDATESUB YR SUBKEY
  I HAS A SUB ITZ CONVEXSUBS'Z SRS SUBKEY
  SUB'Z ACTIVE R FAIL
  SUB'Z GENERATION R SUM OF SUB'Z GENERATION AN 1
  SUB'Z ID R ""
  SUB'Z PATH R ""
  SUB'Z ARGS R "{}"
  SUB'Z HASLAST R FAIL
  SUB'Z LASTVALUE R ""
IF U SAY SO

HOW IZ I CONVEXSUBSCRIBE YR SUBSCRIPTIONID AN YR PATH AN YR ARGS
  I HAS A SUBKEY ITZ I IZ CONVEXFINDSUB YR SUBSCRIPTIONID MKAY
  DIFFRINT SUBKEY AN "", O RLY?
    YA RLY
      I HAS A OLD ITZ CONVEXSUBS'Z SRS SUBKEY
      I HAS A OLDQUERY ITZ OLD'Z QUERYID
      I IZ CONVEXINVALIDATESUB YR SUBKEY MKAY
      CONVEXCONNECTED, O RLY?
        YA RLY
          NOT I IZ TRANSPORT'Z WSSEND YR CONVEXSOCKET AN YR I IZ CONVEXREMOVEMESSAGE YR OLDQUERY MKAY AN YR 250 MKAY, O RLY?
            YA RLY
              I IZ CONVEXSCHEDULERECONNECT YR "RemoveWriteFailed" AN YR "TransportError" MKAY
              FOUND YR FAIL
          OIC
          CONVEXQUERYSET R SUM OF CONVEXQUERYSET AN 1
      OIC
    NO WAI
      SUBKEY R I IZ CONVEXFREESUB MKAY
  OIC
  BOTH SAEM SUBKEY AN "", O RLY?
    YA RLY
      FOUND YR FAIL
  OIC
  I HAS A SUB ITZ CONVEXSUBS'Z SRS SUBKEY
  SUB'Z ACTIVE R WIN
  SUB'Z GENERATION R SUM OF SUB'Z GENERATION AN 1
  SUB'Z ID R SUBSCRIPTIONID
  SUB'Z PATH R PATH
  SUB'Z ARGS R ARGS
  SUB'Z QUERYID R CONVEXNEXTQUERY
  SUB'Z REHYDRATING R FAIL
  SUB'Z HASLAST R FAIL
  CONVEXNEXTQUERY R SUM OF CONVEXNEXTQUERY AN 1
  NOT CONVEXCONNECTED, O RLY?
    YA RLY
      NOT I IZ CONVEXCONNECTLIVE MKAY, O RLY?
        YA RLY
          I IZ CONVEXINVALIDATESUB YR SUBKEY MKAY
          FOUND YR FAIL
      OIC
      FOUND YR WIN
  OIC
  NOT I IZ TRANSPORT'Z WSSEND YR CONVEXSOCKET AN YR I IZ CONVEXADDMESSAGE YR SUBKEY MKAY AN YR 250 MKAY, O RLY?
    YA RLY
      I IZ CONVEXSCHEDULERECONNECT YR "AddWriteFailed" AN YR "TransportError" MKAY
      I IZ CONVEXINVALIDATESUB YR SUBKEY MKAY
      FOUND YR FAIL
  OIC
  CONVEXQUERYSET R SUM OF CONVEXQUERYSET AN 1
  FOUND YR WIN
IF U SAY SO

HOW IZ I CONVEXUNSUBSCRIBE YR SUBSCRIPTIONID
  I HAS A SUBKEY ITZ I IZ CONVEXFINDSUB YR SUBSCRIPTIONID MKAY
  BOTH SAEM SUBKEY AN "", O RLY?
    YA RLY
      FOUND YR WIN
  OIC
  I HAS A SUB ITZ CONVEXSUBS'Z SRS SUBKEY
  I HAS A QUERYID ITZ SUB'Z QUERYID
  I IZ CONVEXINVALIDATESUB YR SUBKEY MKAY
  CONVEXCONNECTED, O RLY?
    YA RLY
      NOT I IZ TRANSPORT'Z WSSEND YR CONVEXSOCKET AN YR I IZ CONVEXREMOVEMESSAGE YR QUERYID MKAY AN YR 250 MKAY, O RLY?
        YA RLY
          I IZ CONVEXSCHEDULERECONNECT YR "RemoveWriteFailed" AN YR "TransportError" MKAY
          FOUND YR FAIL
      OIC
      CONVEXQUERYSET R SUM OF CONVEXQUERYSET AN 1
  OIC
  FOUND YR WIN
IF U SAY SO

HOW IZ I CONVEXDEBUGDISCONNECT
  NOT CONVEXCONNECTED, O RLY?
    YA RLY
      FOUND YR FAIL
  OIC
  BTW The old socket is retired before a reconnect can be acknowledged.
  I IZ TRANSPORT'Z WSDISCONNECT YR CONVEXSOCKET MKAY
  I IZ TRANSPORT'Z WSFREE YR CONVEXSOCKET MKAY
  CONVEXCONNECTED R FAIL
  CONVEXCONNECTIONCOUNT R SUM OF CONVEXCONNECTIONCOUNT AN 1
  CONVEXLASTCLOSE R "DebugDisconnect"
  CONVEXQUERYSET R 0
  CONVEXREMOTEQUERYSET R 0
  CONVEXREMOTEIDENTITY R 0
  CONVEXREMOTETS R "AAAAAAAAAAA="
  IM IN YR DEBUGREHYDRATE UPPIN YR INDEX TIL BOTH SAEM INDEX AN 16
    I HAS A KEY ITZ I IZ CONVEXSLOTKEY YR INDEX MKAY
    I HAS A SUB ITZ CONVEXSUBS'Z SRS KEY
    SUB'Z ACTIVE, O RLY?
      YA RLY
        SUB'Z REHYDRATING R WIN
    OIC
  IM OUTTA YR DEBUGREHYDRATE
  FOUND YR I IZ CONVEXCONNECTLIVE MKAY
IF U SAY SO

HOW IZ I CONVEXVERSION YR ROOT AN YR NAME
  I HAS A RESULT ITZ A BUKKIT
  RESULT HAS A OK ITZ FAIL
  RESULT HAS A QUERYSET ITZ 0
  RESULT HAS A IDENTITY ITZ 0
  RESULT HAS A TS ITZ ""
  NOT I IZ TRANSPORT'Z JSONHAS YR ROOT AN YR NAME MKAY, O RLY?
    YA RLY
      FOUND YR RESULT
  OIC
  I HAS A VERSION ITZ I IZ TRANSPORT'Z JSONGET YR ROOT AN YR NAME MKAY
  DIFFRINT I IZ TRANSPORT'Z JSONTYPE YR VERSION MKAY AN "object", O RLY?
    YA RLY
      FOUND YR RESULT
  OIC
  RESULT'Z QUERYSET R I IZ TRANSPORT'Z JSONINTEGER YR I IZ TRANSPORT'Z JSONGET YR VERSION AN YR "querySet" MKAY MKAY
  RESULT'Z IDENTITY R I IZ TRANSPORT'Z JSONINTEGER YR I IZ TRANSPORT'Z JSONGET YR VERSION AN YR "identity" MKAY MKAY
  RESULT'Z TS R I IZ TRANSPORT'Z JSONSTRING YR I IZ TRANSPORT'Z JSONGET YR VERSION AN YR "ts" MKAY MKAY
  BOTH OF DIFFRINT RESULT'Z QUERYSET AN "" AN BOTH OF DIFFRINT RESULT'Z IDENTITY AN "" AN DIFFRINT RESULT'Z TS AN "", O RLY?
    YA RLY
      RESULT'Z OK R WIN
  OIC
  FOUND YR RESULT
IF U SAY SO

HOW IZ I CONVEXVALIDMOD YR MODIFICATION
  DIFFRINT I IZ TRANSPORT'Z JSONTYPE YR MODIFICATION MKAY AN "object", O RLY?
    YA RLY
      FOUND YR FAIL
  OIC
  I HAS A TYPE ITZ I IZ TRANSPORT'Z JSONSTRING YR I IZ TRANSPORT'Z JSONGET YR MODIFICATION AN YR "type" MKAY MKAY
  I HAS A QUERYID ITZ I IZ TRANSPORT'Z JSONINTEGER YR I IZ TRANSPORT'Z JSONGET YR MODIFICATION AN YR "queryId" MKAY MKAY
  BOTH SAEM QUERYID AN "", O RLY?
    YA RLY
      FOUND YR FAIL
  OIC
  BOTH SAEM TYPE AN "QueryUpdated", O RLY?
    YA RLY
      FOUND YR I IZ TRANSPORT'Z JSONHAS YR MODIFICATION AN YR "value" MKAY
  OIC
  BOTH SAEM TYPE AN "QueryFailed", O RLY?
    YA RLY
      FOUND YR BOTH OF I IZ TRANSPORT'Z JSONHAS YR MODIFICATION AN YR "errorMessage" MKAY AN BOTH SAEM I IZ TRANSPORT'Z JSONTYPE YR I IZ TRANSPORT'Z JSONGET YR MODIFICATION AN YR "errorMessage" MKAY MKAY AN "string"
  OIC
  FOUND YR BOTH SAEM TYPE AN "QueryRemoved"
IF U SAY SO

HOW IZ I CONVEXHANDLETRANSITION YR ROOT
  I HAS A START ITZ I IZ CONVEXVERSION YR ROOT AN YR "startVersion" MKAY
  I HAS A END ITZ I IZ CONVEXVERSION YR ROOT AN YR "endVersion" MKAY
  NOT BOTH OF START'Z OK AN END'Z OK, O RLY?
    YA RLY
      I IZ TRANSPORT'Z DIAG YR "Transition version shape failed" MKAY
      FOUND YR FAIL
  OIC
  NOT BOTH OF BOTH SAEM MAEK START'Z QUERYSET A NUMBR AN CONVEXREMOTEQUERYSET AN BOTH OF BOTH SAEM MAEK START'Z IDENTITY A NUMBR AN CONVEXREMOTEIDENTITY AN BOTH SAEM START'Z TS AN CONVEXREMOTETS, O RLY?
    YA RLY
      I IZ TRANSPORT'Z DIAG YR SMOOSH "Transition start mismatch q=" AN START'Z QUERYSET AN "/" AN CONVEXREMOTEQUERYSET AN " i=" AN START'Z IDENTITY AN "/" AN CONVEXREMOTEIDENTITY AN " ts=" AN START'Z TS AN "/" AN CONVEXREMOTETS MKAY MKAY
      FOUND YR FAIL
  OIC
  I HAS A MODIFICATIONS ITZ I IZ TRANSPORT'Z JSONGET YR ROOT AN YR "modifications" MKAY
  I HAS A COUNT ITZ I IZ TRANSPORT'Z JSONARRAYLEN YR MODIFICATIONS MKAY
  DIFFRINT SMALLR OF COUNT AN 0 AN 0, O RLY?
    YA RLY
      I IZ TRANSPORT'Z DIAG YR "Transition modifications were not an array" MKAY
      FOUND YR FAIL
  OIC
  BTW Validate the complete immutable transition before publishing any event.
  IM IN YR VALIDATELOOP UPPIN YR INDEX TIL BOTH SAEM INDEX AN COUNT
    NOT I IZ CONVEXVALIDMOD YR I IZ TRANSPORT'Z JSONARRAYAT YR MODIFICATIONS AN YR INDEX MKAY MKAY, O RLY?
      YA RLY
        I IZ TRANSPORT'Z DIAG YR SMOOSH "Transition modification invalid: " AN I IZ TRANSPORT'Z JSONARRAYAT YR MODIFICATIONS AN YR INDEX MKAY MKAY MKAY
        FOUND YR FAIL
    OIC
  IM OUTTA YR VALIDATELOOP
  IM IN YR APPLYLOOP UPPIN YR INDEX TIL BOTH SAEM INDEX AN COUNT
    I HAS A MODIFICATION ITZ I IZ TRANSPORT'Z JSONARRAYAT YR MODIFICATIONS AN YR INDEX MKAY
    I HAS A QUERYID ITZ I IZ TRANSPORT'Z JSONINTEGER YR I IZ TRANSPORT'Z JSONGET YR MODIFICATION AN YR "queryId" MKAY MKAY
    I HAS A SUBKEY ITZ I IZ CONVEXFINDQUERY YR QUERYID MKAY
    DIFFRINT SUBKEY AN "", O RLY?
      YA RLY
        I HAS A SUB ITZ CONVEXSUBS'Z SRS SUBKEY
        I HAS A TYPE ITZ I IZ TRANSPORT'Z JSONSTRING YR I IZ TRANSPORT'Z JSONGET YR MODIFICATION AN YR "type" MKAY MKAY
        BOTH SAEM TYPE AN "QueryUpdated", O RLY?
          YA RLY
            I HAS A VALUE ITZ I IZ TRANSPORT'Z JSONGET YR MODIFICATION AN YR "value" MKAY
            I HAS A UNCHANGED ITZ BOTH OF SUB'Z HASLAST AN I IZ TRANSPORT'Z JSONEQUAL YR SUB'Z LASTVALUE AN YR VALUE MKAY
            I HAS A SUPPRESS ITZ BOTH OF SUB'Z REHYDRATING AN UNCHANGED
            SUB'Z LASTVALUE R VALUE
            SUB'Z HASLAST R WIN
            SUB'Z REHYDRATING R FAIL
            NOT SUPPRESS, O RLY?
              YA RLY
                I HAS A EVENT ITZ "{}"
                EVENT R I IZ TRANSPORT'Z JSONSET YR EVENT AN YR "type" AN YR I IZ CONVEXJSONSTRING YR "subscription" MKAY MKAY
                EVENT R I IZ TRANSPORT'Z JSONSET YR EVENT AN YR "subscriptionId" AN YR I IZ CONVEXJSONSTRING YR SUB'Z ID MKAY MKAY
                EVENT R I IZ TRANSPORT'Z JSONSET YR EVENT AN YR "value" AN YR VALUE MKAY
                I HAS A LOGS ITZ "[]"
                I IZ TRANSPORT'Z JSONHAS YR MODIFICATION AN YR "logLines" MKAY, O RLY?
                  YA RLY
                    LOGS R I IZ TRANSPORT'Z JSONGET YR MODIFICATION AN YR "logLines" MKAY
                OIC
                EVENT R I IZ TRANSPORT'Z JSONSET YR EVENT AN YR "logs" AN YR LOGS MKAY
                I IZ CONVEXENQUEUE YR EVENT AN YR SUBKEY AN YR SUB'Z GENERATION MKAY
            OIC
          NO WAI
            BOTH SAEM TYPE AN "QueryFailed", O RLY?
              YA RLY
                I HAS A MESSAGE ITZ I IZ TRANSPORT'Z JSONSTRING YR I IZ TRANSPORT'Z JSONGET YR MODIFICATION AN YR "errorMessage" MKAY MKAY
                I HAS A DATA ITZ "null"
                I IZ TRANSPORT'Z JSONHAS YR MODIFICATION AN YR "errorData" MKAY, O RLY?
                  YA RLY
                    DATA R I IZ TRANSPORT'Z JSONGET YR MODIFICATION AN YR "errorData" MKAY
                OIC
                SUB'Z HASLAST R FAIL
                SUB'Z REHYDRATING R FAIL
                I IZ CONVEXSUBERROR YR SUBKEY AN YR "FunctionError" AN YR MESSAGE AN YR DATA MKAY
            OIC
        OIC
    OIC
  IM OUTTA YR APPLYLOOP
  CONVEXREMOTEQUERYSET R MAEK END'Z QUERYSET A NUMBR
  CONVEXREMOTEIDENTITY R MAEK END'Z IDENTITY A NUMBR
  CONVEXREMOTETS R END'Z TS
  CONVEXMAXTS R END'Z TS
  FOUND YR WIN
IF U SAY SO

HOW IZ I CONVEXLIVETICK
  I HAS A PENDING ITZ I IZ CONVEXTAKEEVENT MKAY
  DIFFRINT PENDING AN "", O RLY?
    YA RLY
      FOUND YR PENDING
  OIC
  NOT CONVEXCONNECTED, O RLY?
    YA RLY
      BOTH OF I IZ CONVEXHASACTIVESUB MKAY AN DIFFRINT SMALLR OF TRANSPORT IZ NOW MKAY AN CONVEXRECONNECTAT AN TRANSPORT IZ NOW MKAY, O RLY?
        YA RLY
          NOT I IZ CONVEXCONNECTLIVE MKAY, O RLY?
            YA RLY
              CONVEXCONNECTIONCOUNT R SUM OF CONVEXCONNECTIONCOUNT AN 1
              CONVEXLASTCLOSE R "ConnectFailed"
              CONVEXRECONNECTAT R SUM OF TRANSPORT IZ NOW MKAY AN CONVEXBACKOFF
              CONVEXBACKOFF R SMALLR OF PRODUKT OF CONVEXBACKOFF AN 2 AN 15000
          OIC
      OIC
      FOUND YR ""
  OIC
  BTW A frame gets one bounded second to complete once any byte is consumed.
  BTW On timeout the RFC6455 primitive retires partial parser state safely.
  I HAS A MESSAGE ITZ I IZ TRANSPORT'Z WSRECEIVE YR CONVEXSOCKET AN YR 1000 MKAY
  I HAS A STATUS ITZ I IZ TRANSPORT'Z WSSTATUS YR CONVEXSOCKET MKAY
  BOTH SAEM STATUS AN 0, O RLY?
    YA RLY
      FOUND YR ""
  OIC
  DIFFRINT STATUS AN 1, O RLY?
    YA RLY
      I IZ TRANSPORT'Z DIAG YR SMOOSH "Live receive status " AN STATUS AN ": " AN I IZ TRANSPORT'Z WSERROR YR CONVEXSOCKET MKAY MKAY MKAY
      I IZ CONVEXSCHEDULERECONNECT YR "LiveReadFailed" AN YR "TransportError" MKAY
      FOUND YR I IZ CONVEXTAKEEVENT MKAY
  OIC
  NOT I IZ TRANSPORT'Z JSONVALID YR MESSAGE MKAY, O RLY?
    YA RLY
      I IZ CONVEXSCHEDULERECONNECT YR "InvalidLiveJSON" AN YR "ProtocolError" MKAY
      FOUND YR I IZ CONVEXTAKEEVENT MKAY
  OIC
  I HAS A TYPE ITZ I IZ TRANSPORT'Z JSONSTRING YR I IZ TRANSPORT'Z JSONGET YR MESSAGE AN YR "type" MKAY MKAY
  BOTH SAEM TYPE AN "Transition", O RLY?
    YA RLY
      NOT I IZ CONVEXHANDLETRANSITION YR MESSAGE MKAY, O RLY?
        YA RLY
          I IZ CONVEXSCHEDULERECONNECT YR "InvalidTransition" AN YR "ProtocolError" MKAY
      OIC
      FOUND YR I IZ CONVEXTAKEEVENT MKAY
  OIC
  EITHER OF BOTH SAEM TYPE AN "Ping" AN EITHER OF BOTH SAEM TYPE AN "MutationResponse" AN BOTH SAEM TYPE AN "ActionResponse", O RLY?
    YA RLY
      FOUND YR ""
  OIC
  I IZ CONVEXSCHEDULERECONNECT YR "UnknownLiveMessage" AN YR "ProtocolError" MKAY
  FOUND YR I IZ CONVEXTAKEEVENT MKAY
IF U SAY SO

HOW IZ I CONVEXCLOSELIVE
  IM IN YR CLOSELOOP UPPIN YR INDEX TIL BOTH SAEM INDEX AN 16
    I HAS A KEY ITZ I IZ CONVEXSLOTKEY YR INDEX MKAY
    I IZ CONVEXINVALIDATESUB YR KEY MKAY
  IM OUTTA YR CLOSELOOP
  CONVEXCONNECTED, O RLY?
    YA RLY
      I IZ TRANSPORT'Z WSCLOSE YR CONVEXSOCKET AN YR 250 MKAY
      I IZ TRANSPORT'Z WSFREE YR CONVEXSOCKET MKAY
      CONVEXCONNECTED R FAIL
  OIC
  FOUND YR WIN
IF U SAY SO

KTHXBYE
