<?php
declare(strict_types=1);
// TCP is the harness mode. This opens the real adapter process and confirms it
// responds immediately to hello and cleanly terminates after close.
$port=0;$probe=stream_socket_server('tcp://127.0.0.1:0',$n,$e);$port=(int)substr(strrchr(stream_socket_get_name($probe,false),':'),1);fclose($probe);
$pipes=[];$env=['ADAPTER_LISTEN'=>"127.0.0.1:$port",'CONVEX_CLIENT_PATH'=>__DIR__.'/convex.php'];$process=proc_open([PHP_BINARY,__DIR__.'/tests/conformance/adapter.php'],[0=>['pipe','r'],1=>['pipe','w'],2=>['pipe','w']],$pipes,null,$env);
for($i=0;$i<30;$i++){ $socket=@stream_socket_client("tcp://127.0.0.1:$port",$x,$y,.05);if($socket)break;usleep(20000); }if(!$socket)throw new RuntimeException('adapter TCP did not listen');
fwrite($socket,"{\"protocolVersion\":1,\"id\":\"h\",\"op\":\"hello\"}\n");$ready=json_decode(fgets($socket),true,512,JSON_THROW_ON_ERROR);if(($ready['type']??'')!=='ready'||($ready['language']??'')!=='php')throw new RuntimeException('adapter hello serialization');
fwrite($socket,"{\"id\":\"c\",\"op\":\"close\"}\n");$closed=json_decode(fgets($socket),true,512,JSON_THROW_ON_ERROR);if(($closed['type']??'')!=='closed')throw new RuntimeException('adapter close serialization');fclose($socket);proc_close($process);echo "php adapter TCP fixture passed\n";
// Stdio mode serializes the real HTTP result, logs, and FunctionError rather
// than returning PHP objects to the harness.
$probe=stream_socket_server('tcp://127.0.0.1:0',$n,$e);$port=(int)substr(strrchr(stream_socket_get_name($probe,false),':'),1);fclose($probe);$server=proc_open([PHP_BINARY,__DIR__.'/fixture_server.php','http',(string)$port],[0=>['pipe','r'],1=>['pipe','w'],2=>['pipe','w']],$serverPipes);usleep(100000);
$pipes=[];$env=['CONVEX_URL'=>"http://127.0.0.1:$port",'CONVEX_CLIENT_PATH'=>__DIR__.'/convex.php'];$process=proc_open([PHP_BINARY,__DIR__.'/tests/conformance/adapter.php'],[0=>['pipe','r'],1=>['pipe','w'],2=>['pipe','w']],$pipes,null,$env);fwrite($pipes[0],"{\"id\":\"q\",\"op\":\"query\",\"path\":\"demo:echo\",\"args\":{}}\n{\"id\":\"f\",\"op\":\"query\",\"path\":\"demo:fail\",\"args\":{}}\n{\"id\":\"c\",\"op\":\"close\"}\n");fclose($pipes[0]);$one=json_decode(fgets($pipes[1]),true,512,JSON_THROW_ON_ERROR);$two=json_decode(fgets($pipes[1]),true,512,JSON_THROW_ON_ERROR);$three=json_decode(fgets($pipes[1]),true,512,JSON_THROW_ON_ERROR);if(($one['type']??'')!=='result'||$one['logs']!==['ok']||($two['error']['data']['code']??'')!=='ROOM_EMPTY'||$two['logs']!==['failed']||($three['type']??'')!=='closed')throw new RuntimeException('adapter result/error serialization');proc_close($process);proc_close($server);echo "php adapter HTTP serialization fixture passed\n";
// The adapter-only disconnect command must ack only after a genuine reconnect.
// The peer validates connectionCount and Add on both sockets, then Remove.
$probe=stream_socket_server('tcp://127.0.0.1:0',$n,$e);$port=(int)substr(strrchr(stream_socket_get_name($probe,false),':'),1);fclose($probe);$server=proc_open([PHP_BINARY,__DIR__.'/fixture_server.php','adapterdebug',(string)$port],[0=>['pipe','r'],1=>['pipe','w'],2=>['pipe','w']],$serverPipes);usleep(100000);$pipes=[];$env=['CONVEX_URL'=>"http://127.0.0.1:$port",'CONVEX_CLIENT_PATH'=>__DIR__.'/convex.php'];$process=proc_open([PHP_BINARY,__DIR__.'/tests/conformance/adapter.php'],[0=>['pipe','r'],1=>['pipe','w'],2=>['pipe','w']],$pipes,null,$env);fwrite($pipes[0],"{\"id\":\"s\",\"op\":\"subscribe\",\"subscriptionId\":\"live\",\"path\":\"demo:state\",\"args\":{}}\n");$ack=json_decode(fgets($pipes[1]),true);$initial=json_decode(fgets($pipes[1]),true);if(($ack['type']??'')!=='ack'||($initial['value']['count']??-1)!==0)throw new RuntimeException('adapter initial Live');fwrite($pipes[0],"{\"id\":\"d\",\"op\":\"debugDisconnect\"}\n");$ack=json_decode(fgets($pipes[1]),true);$recovered=json_decode(fgets($pipes[1]),true);if(($ack['type']??'')!=='ack'||($recovered['value']['count']??-1)!==1)throw new RuntimeException('adapter debug reconnect');fwrite($pipes[0],"{\"id\":\"u\",\"op\":\"unsubscribe\",\"subscriptionId\":\"live\"}\n{\"id\":\"c\",\"op\":\"close\"}\n");fclose($pipes[0]);$unsub=json_decode(fgets($pipes[1]),true);$closed=json_decode(fgets($pipes[1]),true);if(($unsub['type']??'')!=='ack'||($closed['type']??'')!=='closed')throw new RuntimeException('adapter reconnect close');proc_close($process);if(proc_close($server)!==0)throw new RuntimeException('adapter debug peer assertions');echo "php adapter debugDisconnect fixture passed\n";
// A malformed Live message is an NDJSON subscription error, not stderr. The
// next valid transition on that same subscription proves recovery.
$probe=stream_socket_server('tcp://127.0.0.1:0',$n,$e);$port=(int)substr(strrchr(stream_socket_get_name($probe,false),':'),1);fclose($probe);$server=proc_open([PHP_BINARY,__DIR__.'/fixture_server.php','protocol',(string)$port],[0=>['pipe','r'],1=>['pipe','w'],2=>['pipe','w']],$serverPipes);usleep(100000);$pipes=[];$env=['CONVEX_URL'=>"http://127.0.0.1:$port",'CONVEX_CLIENT_PATH'=>__DIR__.'/convex.php'];$process=proc_open([PHP_BINARY,__DIR__.'/tests/conformance/adapter.php'],[0=>['pipe','r'],1=>['pipe','w'],2=>['pipe','w']],$pipes,null,$env);fwrite($pipes[0],"{\"id\":\"s\",\"op\":\"subscribe\",\"subscriptionId\":\"bad\",\"path\":\"demo:state\",\"args\":{}}\n");$ack=json_decode(fgets($pipes[1]),true);$error=json_decode(fgets($pipes[1]),true);$recovered=json_decode(fgets($pipes[1]),true);if(($ack['type']??'')!=='ack'||($error['type']??'')!=='subscription'||($error['subscriptionId']??'')!=='bad'||($error['error']['name']??'')!=='ProtocolError'||($recovered['value']['count']??-1)!==7)throw new RuntimeException('adapter protocol error recovery');fwrite($pipes[0],"{\"id\":\"u\",\"op\":\"unsubscribe\",\"subscriptionId\":\"bad\"}\n{\"id\":\"c\",\"op\":\"close\"}\n");fclose($pipes[0]);fgets($pipes[1]);fgets($pipes[1]);proc_close($process);proc_close($server);echo "php adapter protocol recovery fixture passed\n";
// Keep the socket open with no Live bytes. The controller can still send close
// and receive `closed` promptly because pumping never owns a blocking read.
$probe=stream_socket_server('tcp://127.0.0.1:0',$n,$e);$port=(int)substr(strrchr(stream_socket_get_name($probe,false),':'),1);fclose($probe);$server=proc_open([PHP_BINARY,__DIR__.'/fixture_server.php','blocked',(string)$port],[0=>['pipe','r'],1=>['pipe','w'],2=>['pipe','w']],$serverPipes);usleep(100000);$pipes=[];$env=['CONVEX_URL'=>"http://127.0.0.1:$port",'CONVEX_CLIENT_PATH'=>__DIR__.'/convex.php'];$process=proc_open([PHP_BINARY,__DIR__.'/tests/conformance/adapter.php'],[0=>['pipe','r'],1=>['pipe','w'],2=>['pipe','w']],$pipes,null,$env);fwrite($pipes[0],"{\"id\":\"s\",\"op\":\"subscribe\",\"subscriptionId\":\"blocked\",\"path\":\"demo:state\",\"args\":{}}\n");fgets($pipes[1]);$start=microtime(true);fwrite($pipes[0],"{\"id\":\"c\",\"op\":\"close\"}\n");$closed=json_decode(fgets($pipes[1]),true);if(($closed['type']??'')!=='closed'||microtime(true)-$start>.3)throw new RuntimeException('adapter blocked Live close');fclose($pipes[0]);proc_close($process);proc_close($server);echo "php adapter blocked-close fixture passed\n";
