<?php
declare(strict_types=1);
[$_, $role, $port]=$argv;$s=stream_socket_server("tcp://127.0.0.1:$port",$n,$e);if(!$s)throw new RuntimeException($e);
function head($c):string{$h='';while(!str_contains($h,"\r\n\r\n"))$h.=fread($c,1);return $h;}
function outframe(string $p,bool $fin=true,int $op=1):string{$n=strlen($p);return chr(($fin?128:0)|$op).($n<126?chr($n):chr(126).pack('n',$n)).$p;}
function exact($c,int $n):string{$v='';while(strlen($v)<$n){$x=fread($c,$n-strlen($v));if($x===''||$x===false)throw new RuntimeException('peer closed');$v.=$x;}return $v;}
function clientFrame($c):array{$h=exact($c,2);$a=ord($h[0]);$b=ord($h[1]);$n=$b&127;if($n===126)$n=unpack('n',exact($c,2))[1];$mask=exact($c,4);$data=exact($c,$n);for($i=0;$i<$n;$i++)$data[$i]=$data[$i]^$mask[$i%4];return [$a&15,json_decode($data,true)];}
if($role==='http'){for($i=0;$i<2;$i++){$c=stream_socket_accept($s,3);$h=head($c);preg_match('/Content-Length: (\d+)/i',$h,$m);$body=fread($c,(int)($m[1]??0));$q=json_decode($body,true);$fail=($q['path']??'')==='demo:fail';$json=json_encode($fail?['status'=>'error','errorMessage'=>'ROOM_EMPTY','errorData'=>['code'=>'ROOM_EMPTY'],'logLines'=>['failed']]:['status'=>'success','value'=>['nested'=>['utf8'=>'é']],'logLines'=>['ok']]);fwrite($c,"HTTP/1.1 200 OK\r\nContent-Length: ".strlen($json)."\r\n\r\n$json");fclose($c);}}
elseif($role==='reconnect'){for($i=0;$i<6;$i++){$c=stream_socket_accept($s,4);$h=head($c);preg_match('/Sec-WebSocket-Key: (.+)\r/i',$h,$m);$a=base64_encode(sha1(trim($m[1]).'258EAFA5-E914-47DA-95CA-C5AB0DC85B11',true));fwrite($c,"HTTP/1.1 101 Switching Protocols\r\nUpgrade: websocket\r\nConnection: Upgrade\r\nSec-WebSocket-Accept: $a\r\n\r\n");[$op,$connect]=clientFrame($c);[$op2,$add]=clientFrame($c);if(($connect['connectionCount']??-1)!==$i||($connect['type']??'')!=='Connect'||($add['modifications'][0]['type']??'')!=='Add')exit(2);$zero=['querySet'=>0,'identity'=>0,'ts'=>'AAAAAAAAAAA='];$one=['querySet'=>1,'identity'=>0,'ts'=>base64_encode(pack('V',$i+1).str_repeat("\0",4))];$x=json_encode(['type'=>'Transition','startVersion'=>$zero,'endVersion'=>$one,'modifications'=>[['type'=>'QueryUpdated','queryId'=>0,'value'=>['count'=>$i],'logLines'=>[]]]]);fwrite($c,outframe($x));if($i===5){[$op3,$remove]=clientFrame($c);if(($remove['modifications'][0]['type']??'')!=='Remove'||($remove['baseVersion']??-1)!==1||($remove['newVersion']??-1)!==2)exit(3);}fclose($c);}}
elseif($role==='blocked'){$c=stream_socket_accept($s,3);$h=head($c);preg_match('/Sec-WebSocket-Key: (.+)\r/i',$h,$m);$a=base64_encode(sha1(trim($m[1]).'258EAFA5-E914-47DA-95CA-C5AB0DC85B11',true));fwrite($c,"HTTP/1.1 101 Switching Protocols\r\nUpgrade: websocket\r\nConnection: Upgrade\r\nSec-WebSocket-Accept: $a\r\n\r\n");usleep(800000);fclose($c);}
else {$c=stream_socket_accept($s,3);$h=head($c);preg_match('/Sec-WebSocket-Key: (.+)\r/i',$h,$m);$a=base64_encode(sha1(trim($m[1]).'258EAFA5-E914-47DA-95CA-C5AB0DC85B11',true));fwrite($c,"HTTP/1.1 101 Switching Protocols\r\nUpgrade: websocket\r\nConnection: Upgrade\r\nSec-WebSocket-Accept: $a\r\n\r\n");usleep(150000);$v0=['querySet'=>0,'identity'=>0,'ts'=>'AAAAAAAAAAA='];$v1=['querySet'=>1,'identity'=>0,'ts'=>'AQAAAAAAAAA='];$x=json_encode(['type'=>'Transition','startVersion'=>$v0,'endVersion'=>$v1,'modifications'=>[['type'=>'QueryFailed','queryId'=>0,'errorMessage'=>'ROOM_EMPTY','errorData'=>['code'=>'ROOM_EMPTY'],'logLines'=>['empty']]]],JSON_UNESCAPED_UNICODE);fwrite($c,outframe(substr($x,0,11),false).outframe(substr($x,11),true,0));usleep(100000);$v2=['querySet'=>1,'identity'=>0,'ts'=>'AgAAAAAAAAA='];$x=json_encode(['type'=>'Transition','startVersion'=>$v1,'endVersion'=>$v2,'modifications'=>[['type'=>'QueryUpdated','queryId'=>0,'value'=>['count'=>1,'word'=>'é'],'logLines'=>['recovered']]]],JSON_UNESCAPED_UNICODE);fwrite($c,outframe($x));usleep(150000);fclose($c);}
fclose($s);
