HAI 1.3

I HAS A QUERYRESULT ITZ I IZ CONVEXQUERY YR "counter:get" AN YR "{}" MKAY
NOT QUERYRESULT'Z OK, O RLY?
  YA RLY
    I IZ TRANSPORT'Z ABORT YR QUERYRESULT'Z ERRORMESSAGE MKAY
OIC
DIFFRINT I IZ TRANSPORT'Z JSONINTEGER YR QUERYRESULT'Z VALUE MKAY AN "0", O RLY?
  YA RLY
    I IZ TRANSPORT'Z ABORT YR "integral decimal response was not accepted" MKAY
OIC
DIFFRINT I IZ TRANSPORT'Z JSONARRAYLEN YR QUERYRESULT'Z LOGS MKAY AN 1, O RLY?
  YA RLY
    I IZ TRANSPORT'Z ABORT YR "HTTP logs were not preserved" MKAY
OIC

I HAS A FAILRESULT ITZ I IZ CONVEXACTION YR "counter:fail" AN YR "{}" MKAY
FAILRESULT'Z OK, O RLY?
  YA RLY
    I IZ TRANSPORT'Z ABORT YR "FunctionError became a successful value" MKAY
OIC
DIFFRINT FAILRESULT'Z ERRORNAME AN "FunctionError", O RLY?
  YA RLY
    I IZ TRANSPORT'Z ABORT YR "FunctionError name was not preserved" MKAY
OIC
DIFFRINT FAILRESULT'Z ERRORMESSAGE AN "fixture failed", O RLY?
  YA RLY
    I IZ TRANSPORT'Z ABORT YR "FunctionError message was not preserved" MKAY
OIC

I HAS A BADRESULT ITZ I IZ CONVEXQUERY YR "counter:missing" AN YR "{}" MKAY
BADRESULT'Z OK, O RLY?
  YA RLY
    I IZ TRANSPORT'Z ABORT YR "malformed success became a successful value" MKAY
OIC
DIFFRINT BADRESULT'Z ERRORNAME AN "ProtocolError", O RLY?
  YA RLY
    I IZ TRANSPORT'Z ABORT YR "malformed success did not produce ProtocolError" MKAY
OIC

VISIBLE "lolcode HTTP fixtures: ok"
KTHXBYE
