HAI 1.3

HOW IZ I TESTVERSION YR QUERYSET AN YR IDENTITY AN YR TS
  I HAS A VERSION ITZ "{}"
  VERSION R I IZ TRANSPORT'Z JSONSET YR VERSION AN YR "querySet" AN YR QUERYSET MKAY
  VERSION R I IZ TRANSPORT'Z JSONSET YR VERSION AN YR "identity" AN YR IDENTITY MKAY
  VERSION R I IZ TRANSPORT'Z JSONSET YR VERSION AN YR "ts" AN YR I IZ CONVEXJSONSTRING YR TS MKAY MKAY
  FOUND YR VERSION
IF U SAY SO

HOW IZ I TESTTRANSITION YR STARTQUERY AN YR STARTIDENTITY AN YR STARTTS AN YR ENDQUERY AN YR ENDIDENTITY AN YR ENDTS AN YR MODIFICATIONS
  I HAS A TRANSITION ITZ "{}"
  TRANSITION R I IZ TRANSPORT'Z JSONSET YR TRANSITION AN YR "type" AN YR I IZ CONVEXJSONSTRING YR "Transition" MKAY MKAY
  TRANSITION R I IZ TRANSPORT'Z JSONSET YR TRANSITION AN YR "startVersion" AN YR I IZ TESTVERSION YR STARTQUERY AN YR STARTIDENTITY AN YR STARTTS MKAY MKAY
  TRANSITION R I IZ TRANSPORT'Z JSONSET YR TRANSITION AN YR "endVersion" AN YR I IZ TESTVERSION YR ENDQUERY AN YR ENDIDENTITY AN YR ENDTS MKAY MKAY
  TRANSITION R I IZ TRANSPORT'Z JSONSET YR TRANSITION AN YR "modifications" AN YR MODIFICATIONS MKAY
  FOUND YR TRANSITION
IF U SAY SO

HOW IZ I UPDATED YR QUERYID AN YR VALUE
  I HAS A MODIFICATION ITZ "{}"
  MODIFICATION R I IZ TRANSPORT'Z JSONSET YR MODIFICATION AN YR "type" AN YR I IZ CONVEXJSONSTRING YR "QueryUpdated" MKAY MKAY
  MODIFICATION R I IZ TRANSPORT'Z JSONSET YR MODIFICATION AN YR "queryId" AN YR QUERYID MKAY
  MODIFICATION R I IZ TRANSPORT'Z JSONSET YR MODIFICATION AN YR "value" AN YR VALUE MKAY
  MODIFICATION R I IZ TRANSPORT'Z JSONSET YR MODIFICATION AN YR "logLines" AN YR "[]" MKAY
  FOUND YR I IZ TRANSPORT'Z JSONAPPEND YR "[]" AN YR MODIFICATION MKAY
IF U SAY SO

HOW IZ I FAILED YR QUERYID AN YR MESSAGE
  I HAS A MODIFICATION ITZ "{}"
  MODIFICATION R I IZ TRANSPORT'Z JSONSET YR MODIFICATION AN YR "type" AN YR I IZ CONVEXJSONSTRING YR "QueryFailed" MKAY MKAY
  MODIFICATION R I IZ TRANSPORT'Z JSONSET YR MODIFICATION AN YR "queryId" AN YR QUERYID MKAY
  MODIFICATION R I IZ TRANSPORT'Z JSONSET YR MODIFICATION AN YR "errorMessage" AN YR I IZ CONVEXJSONSTRING YR MESSAGE MKAY MKAY
  I HAS A DATA ITZ I IZ TRANSPORT'Z JSONSET YR "{}" AN YR "code" AN YR 7 MKAY
  MODIFICATION R I IZ TRANSPORT'Z JSONSET YR MODIFICATION AN YR "errorData" AN YR DATA MKAY
  FOUND YR I IZ TRANSPORT'Z JSONAPPEND YR "[]" AN YR MODIFICATION MKAY
IF U SAY SO

I HAS A SUB ITZ CONVEXSUBS'Z S0
SUB'Z ACTIVE R WIN
SUB'Z ID R "fixture-sub"
SUB'Z PATH R "counter:get"
SUB'Z ARGS R "{}"
SUB'Z QUERYID R 0
SUB'Z GENERATION R 1

I HAS A INITIAL ITZ I IZ TESTTRANSITION YR 0 AN YR 0 AN YR "AAAAAAAAAAA=" AN YR 1 AN YR 0 AN YR "BBBB" AN YR I IZ UPDATED YR 0 AN YR "0.0" MKAY MKAY
NOT I IZ CONVEXHANDLETRANSITION YR INITIAL MKAY, O RLY?
  YA RLY
    I IZ TRANSPORT'Z ABORT YR "initial QueryUpdated was rejected" MKAY
OIC
I HAS A EVENT ITZ I IZ CONVEXTAKEEVENT MKAY
NOT BOTH OF I IZ TRANSPORT'Z JSONEQUAL YR I IZ TRANSPORT'Z JSONGET YR EVENT AN YR "value" MKAY AN YR "0.0" MKAY AN BOTH SAEM I IZ TRANSPORT'Z JSONSTRING YR I IZ TRANSPORT'Z JSONGET YR EVENT AN YR "subscriptionId" MKAY MKAY AN "fixture-sub", O RLY?
  YA RLY
    I IZ TRANSPORT'Z ABORT YR "initial subscription event was malformed" MKAY
OIC

I HAS A FAILURE ITZ I IZ TESTTRANSITION YR 1 AN YR 0 AN YR "BBBB" AN YR 1 AN YR 1 AN YR "CCCC" AN YR I IZ FAILED YR 0 AN YR "fixture failed" MKAY MKAY
NOT I IZ CONVEXHANDLETRANSITION YR FAILURE MKAY, O RLY?
  YA RLY
    I IZ TRANSPORT'Z ABORT YR "QueryFailed was rejected" MKAY
OIC
EVENT R I IZ CONVEXTAKEEVENT MKAY
DIFFRINT I IZ TRANSPORT'Z JSONSTRING YR I IZ TRANSPORT'Z JSONGET YR I IZ TRANSPORT'Z JSONGET YR EVENT AN YR "error" MKAY AN YR "name" MKAY MKAY AN "FunctionError", O RLY?
  YA RLY
    I IZ TRANSPORT'Z ABORT YR "QueryFailed did not preserve FunctionError" MKAY
OIC

I HAS A RECOVERY ITZ I IZ TESTTRANSITION YR 1 AN YR 1 AN YR "CCCC" AN YR 1 AN YR 2 AN YR "DDDD" AN YR I IZ UPDATED YR 0 AN YR "1" MKAY MKAY
NOT I IZ CONVEXHANDLETRANSITION YR RECOVERY MKAY, O RLY?
  YA RLY
    I IZ TRANSPORT'Z ABORT YR "QueryFailed recovery was rejected" MKAY
OIC
EVENT R I IZ CONVEXTAKEEVENT MKAY
NOT I IZ TRANSPORT'Z JSONEQUAL YR I IZ TRANSPORT'Z JSONGET YR EVENT AN YR "value" MKAY AN YR "1" MKAY, O RLY?
  YA RLY
    I IZ TRANSPORT'Z ABORT YR "recovered value was not delivered" MKAY
OIC

BTW A rehydrated value equal to the last delivered value is suppressed.
SUB'Z REHYDRATING R WIN
I HAS A REHYDRATED ITZ I IZ TESTTRANSITION YR 1 AN YR 2 AN YR "DDDD" AN YR 1 AN YR 3 AN YR "EEEE" AN YR I IZ UPDATED YR 0 AN YR "1.0" MKAY MKAY
NOT I IZ CONVEXHANDLETRANSITION YR REHYDRATED MKAY, O RLY?
  YA RLY
    I IZ TRANSPORT'Z ABORT YR "rehydration transition was rejected" MKAY
OIC
DIFFRINT I IZ CONVEXTAKEEVENT MKAY AN "", O RLY?
  YA RLY
    I IZ TRANSPORT'Z ABORT YR "unchanged rehydration was not suppressed" MKAY
OIC

BTW Invalidation happens before acknowledgement and makes an old relay stale.
I HAS A STALE ITZ "{}"
STALE R I IZ TRANSPORT'Z JSONSET YR STALE AN YR "type" AN YR I IZ CONVEXJSONSTRING YR "subscription" MKAY MKAY
STALE R I IZ TRANSPORT'Z JSONSET YR STALE AN YR "subscriptionId" AN YR I IZ CONVEXJSONSTRING YR "fixture-sub" MKAY MKAY
STALE R I IZ TRANSPORT'Z JSONSET YR STALE AN YR "value" AN YR 2 MKAY
STALE R I IZ TRANSPORT'Z JSONSET YR STALE AN YR "logs" AN YR "[]" MKAY
I IZ CONVEXENQUEUE YR STALE AN YR "S0" AN YR SUB'Z GENERATION MKAY
I IZ CONVEXINVALIDATESUB YR "S0" MKAY
DIFFRINT I IZ CONVEXTAKEEVENT MKAY AN "", O RLY?
  YA RLY
    I IZ TRANSPORT'Z ABORT YR "stale relay crossed invalidation" MKAY
OIC

BTW Count pressure drops oldest events instead of growing without bound.
IM IN YR PRESSURE UPPIN YR INDEX TIL BOTH SAEM INDEX AN 20
  I IZ CONVEXENQUEUE YR I IZ CONVEXJSONSTRING YR SMOOSH "event-" AN INDEX MKAY MKAY AN YR "" AN YR 0 MKAY
IM OUTTA YR PRESSURE
DIFFRINT CONVEXEVENTCOUNT AN 16, O RLY?
  YA RLY
    I IZ TRANSPORT'Z ABORT YR "global event count was not bounded" MKAY
OIC

VISIBLE "lolcode Live state fixtures: ok"
KTHXBYE
