HAI 1.3

I HAS A ENCODED ITZ I IZ CONVEXJSONSTRING YR "HAI: WORLD" MKAY
I IZ TRANSPORT'Z JSONVALID YR ENCODED MKAY, O RLY?
  YA RLY
    VISIBLE "lolcode runtime bindings: ok"
  NO WAI
    I IZ TRANSPORT'Z DIAG YR SMOOSH "unexpected JSON string: " AN ENCODED MKAY MKAY
    FAIL
OIC

KTHXBYE
