HAI 1.3

I HAS A ENCODED ITZ I IZ CONVEXJSONSTRING YR "HAI: WORLD" MKAY
I IZ TRANSPORT'Z JSONVALID YR ENCODED MKAY, O RLY?
  YA RLY
    VISIBLE "lolcode runtime bindings: ok"
  NO WAI
    I IZ TRANSPORT'Z ABORT YR SMOOSH "unexpected JSON string: " AN ENCODED MKAY MKAY
OIC
I HAS A OBJECT ITZ I IZ TRANSPORT'Z JSONSET YR "{}" AN YR "key" AN YR ENCODED MKAY
NOT I IZ TRANSPORT'Z JSONVALID YR OBJECT MKAY, O RLY?
  YA RLY
    I IZ TRANSPORT'Z ABORT YR SMOOSH "JSONSET failed: " AN OBJECT MKAY MKAY
OIC
DIFFRINT I IZ TRANSPORT'Z JSONINTEGER YR "0.0" MKAY AN "0", O RLY?
  YA RLY
    I IZ TRANSPORT'Z ABORT YR "integral decimal was rejected" MKAY
OIC
DIFFRINT I IZ TRANSPORT'Z JSONINTEGER YR "1.5" MKAY AN "", O RLY?
  YA RLY
    I IZ TRANSPORT'Z ABORT YR "fractional number was accepted" MKAY
OIC
DIFFRINT I IZ TRANSPORT'Z JSONINTEGER YR "9007199254740992" MKAY AN "", O RLY?
  YA RLY
    I IZ TRANSPORT'Z ABORT YR "unsafe integer was accepted" MKAY
OIC
NOT I IZ TRANSPORT'Z JSONEQUAL YR "1" AN YR "1.0" MKAY, O RLY?
  YA RLY
    I IZ TRANSPORT'Z ABORT YR "equivalent JSON numbers differed" MKAY
OIC
I IZ TRANSPORT'Z JSONEQUAL YR "9007199254740993" AN YR "9007199254740992.0" MKAY, O RLY?
  YA RLY
    I IZ TRANSPORT'Z ABORT YR "adjacent large JSON integers compared equal" MKAY
OIC
DIFFRINT I IZ STRING'Z LEN YR TRANSPORT IZ RANDOMUUID MKAY MKAY AN 36, O RLY?
  YA RLY
    I IZ TRANSPORT'Z ABORT YR "random UUID shape was invalid" MKAY
OIC

KTHXBYE
