HAI 1.3

I HAS A ENCODED ITZ I IZ CONVEXJSONSTRING YR "HAI: WORLD" MKAY
I IZ TRANSPORT'Z JSONVALID YR ENCODED MKAY, O RLY?
  YA RLY
    VISIBLE "lolcode runtime bindings: ok"
  NO WAI
    I IZ TRANSPORT'Z ABORT YR SMOOSH "unexpected JSON string: " AN ENCODED MKAY MKAY
OIC
I HAS A OBJECT ITZ I IZ TRANSPORT'Z JSONSET YR "{}" AN YR "key" AN YR ENCODED MKAY
NOT I IZ TRANSPORT'Z JSONVALID YR OBJECT MKAY, O RLY?
  YA RLY
    I IZ TRANSPORT'Z ABORT YR SMOOSH "JSONSET failed: " AN OBJECT MKAY MKAY
OIC

KTHXBYE
